steps:
  # Access the id_github file from Secret Manager, and setup SSH
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Pull docker frontend syntax
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:experimental']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:1.0-experimental']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker.io/library/node:alpine']

  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}',
        '--ssh',
        'cloudbuild_github=/root/.ssh/id_rsa',
        '--build-arg',
        'CUSTOMER_ACCOUNT_ID=${_CUSTOMER_ACCOUNT_ID}',
        '--build-arg',
        'API_BASE_URL=${_API_BASE_URL}',
        '--build-arg',
        'WEBSOCKET_BASE_URL=${_WEBSOCKET_BASE_URL}',
        '--build-arg',
        'KEYCLOAK_BASE_URL=${_KEYCLOAK_BASE_URL}',
        '--build-arg',
        'KEYCLOAK_REALM=${_KEYCLOAK_REALM}',
        '--build-arg',
        'KEYCLOAK_CLIENT_ID=${_KEYCLOAK_CLIENT_ID}',
        '.',
      ]
    env:
      - 'DOCKER_BUILDKIT=1'
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}']

  # Deploy image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}',
        '--region',
        'us-central1',
        '--platform',
        'managed',
      ]

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}

timeout: 1200s

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/cloudbuild_github/versions/latest
      env: 'SSH_KEY'
